name: cashflowy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_route: ^9.2.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  dart_code_linter: ^1.1.3
  drift_dev: ^2.20.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
